### PR TITLE
Updates for new RSS bodies

### PR DESCRIPTION
**Pull request by Kerbas-ad-astra**
As requested in KSP-RO/RealSolarSystem#116

New layout and also a couple of new files: "-stock" and "-opm" do the same thing as ribbonator.py for the stock and Outer Planets Mod solar systems, respectively, while "-nereid" iterates through all possible device and body combinations to generate individual ribbons for Final Frontier.

Caveat emptor: I'm using Python 3, so there are some changes that come from that.  Also, I've got some more files to clean up and add here (the layouts and labeled layouts for stock and the Outer Planets Mod), but they can wait.

As for a completely new layout: there are 34 ribbons now, which is not evenly divisible by anything but 2 and 17.  The current layout (based on extending the ribbon bar) is 3 rows x 12 columns, but there are some layouts that look okay if we go to 4 or 6 rows.

New files (some added, some still missing):

- [x] New (3-tall) layout for RSS (Uranian moons, Ceres, Vesta)
- [ ] Consider 4-tall layout?
- [x] New devices for nereid script
- [x] Stock layout (and asteroid layout)
- [x] Labeled version
- [x] OPM layout (and asteroid layout)
- [x] Labeled version

### CODE REVIEW

**Comment by ec429** [comment]
Thanks for this!
But, I'm not sure about your implementation of the -stock etc. versions.  (Though I do like the idea of having support for other solar systems besides RSS!)  They seem to be duplicating the entire code, rather than importing ribbonator and constructing a different set of bodies.  Similarly, the -nereid version should just be a different `main` function operating on the same objects.
I'd say probably go for a set of command line options to choose between the different solar systems.
If you'd prefer not to do that rewrite, I can just merge this and then reshape it in my own image (better, faster, stronger etc. ;)

**Comment by ec429** [comment]
Oh, also, it looks like -stock wants to open "Stock/Layout.png" which doesn't actually exist in the repo.

**Comment by Kerbas-ad-astra** [comment]
Yeah, having a command line switch would be better.  Is it as simple as having e.g. ribbonator-stock call ```import ribbonator```, and then redefining ```layout```. ```asteroid_layout```, and ```bodies```, or should those all be combined into one file that chooses how to initialize those variables based on the first line of the input (e.g. having 'RSS', 'OPM' or 'Stock' before the list of celestial bodies and devices proper)?

I've added a checklist of those files that I still need to add to the top post.

**Comment by ec429** [comment]
Well, really having `layout`, `bodies`, etc. be module-level global variables is a bit ick, so in the long run I'll want to change that to use something a bit better, but yes, `import ribbonator` and altering `ribbonator.layout` and friends should do the job.

**Comment by Kerbas-ad-astra** [comment]
Alright, all required files are present.

**Comment by ec429** [comment]
Can you explain what "Caps Device", "Flag Device" etc. are for and how/why they are different from "Capsule" and "Flag or Monument"?
Also, check indentation; you've got some hard tabs (most noticeable in `ribbonator.py`'s Devices list, because Github renders them as 8 spaces wide).  They should be 4-space indents.

Other than that, really nice work!

**Comment by Kerbas-ad-astra** [comment]
(Indentation is fixed now.)

Those new devices are for the Final Frontier ribbons.  Some of their icons are in a slightly different place than 'stock'.  For example, in Unistrut's ribbon style, the flag is a "craft" device on the right side of the ribbon (an alternative to the capsule, lander, etc.), but in Final Frontier, the flag ribbon is something that is awarded to a Kerbal who plants a flag, and that flag is on the left side of the ribbon (opposite a lander icon).

**Pull request merged**
